apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  strategy: {}
  template:
    metadata: {}
    spec:
      containers:
      - image: delineateio/hello
        name: hello-container
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['ALL']
          readOnlyRootFilesystem: true
      - image: delineateio/hola
        name: hola-container
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['ALL']
          readOnlyRootFilesystem: true
      - image: k8s.gcr.io/echoserver:1.4
        name: hello-whoami
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['ALL']
            add: ['CAP_CHOWN']
